spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: platinadark@gmail.com
    password: ghkdtmdwn1!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true